=== marcosremon/dam1/Lenguaje de marcas/LMSGI/UD6 - DTD y Esquemas XML/XSD/clasM24/ejercicio3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="vehiculos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculo" maxOccurs="unbounded">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Barco" />
                            <xs:enumeration value="Coche" />
                            <xs:enumeration value="Tren" />
                            <xs:enumeration value="Bicicleta" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcosremon/dam1/Lenguaje de marcas/LMSGI/UD6 - DTD y Esquemas XML/XSD/clasM24/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehiculos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicio3.xsd">
    <vehiculo>Coche</vehiculo>
    <vehiculo>Coche</vehiculo>
    <vehiculo>Barco</vehiculo>
    <vehiculo>Coche</vehiculo>
    <vehiculo>Coche</vehiculo>
    <vehiculo>Bicicleta</vehiculo>
    <vehiculo>Coche</vehiculo>
    <vehiculo>Tren</vehiculo>
    <vehiculo>Tren</vehiculo>
</vehiculos>
<!-- Existen 4 posibilidades: Coche, Barco, Bicicleta, Tren-->
