<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo [
    <!ELEMENT catalogo (producto+)>
    <!ELEMENT producto (nombre, descripcion?)>
    <!ATTLIST producto codigo CDATA #IMPLIED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
]>
<catalogo>
    <!--El catalogo lleva uno o mÃ¡s elementos producto-->
    <producto> <!--Producto puede tener un atributo codigo-->
        <nombre>Caja con autocierre</nombre>
        <!--La descripciÃ³n es optativa-->
        <descripcion>Caja de seguridad...</descripcion>
    </producto>
    <producto codigo="jjjjj">
        <nombre>Caja llaves</nombre>
    </producto>
</catalogo>